### ISSUE TITLE
hosts (raspberry-pi): Set up traefik

### ISSUE THREAD

**Issue by britter** [britter/nix-configuration#13]
In order to map from ports that run web apps to subdomains.

```yaml
http:
  routers:
    router0:
      entryPoints:
      - web
      service: service-foo
      rule: Host(`site1…`)
  # Add the service
  services:
    service-foo:
      loadBalancer:
        servers:
        - url: http:mein-raspberry…
```
